#**Ariel Pan, Daniel Lyu**

Spring 2026

CS 443: Bio-inspired Machine Learning

Project 2: Predictive Coding

**#### Extension: Explore more of ConvPCN**

Inspired by the paper **Deep Predictive Coding Network with Local Recurrent Processing for Object Recognition**

Main Changes:
- add an explicit **bypass / skip path** inside each recurrent block
- vary the **pooling schedule**
- vary the **depth / width**

**bypass layer:**

one path: recurrent predictive coding update

second path: direct bypass of lower-level features

final output: combine the two

## Compare multiple architecture variants

**num_steps**: The number of recurrent predictive-coding update iterations performed inside each block during one forward pass; larger values allow more error refinement but increase runtime.


**PCN Units**: The number of convolutional channels in each PCN block, which controls the representational width and capacity of the network at different depths.


**MaxPool After Block**: A tuple indicating whether max pooling is applied after each block, which reduces spatial resolution and increases the effective receptive field in deeper layers.


**Bypass (Skip)**: Whether each block includes a shortcut path that carries lower-level features directly forward, improving information flow and making optimization easier.


**Depth (#blocks)**: The total number of predictive-coding blocks stacked in the architecture, which determines how hierarchical and deep the model is.

## 1) Imports and setup

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import os
os.environ["TF_GPU_ALLOCATOR"] = "cuda_malloc_async"
import tensorflow as tf
gpus = tf.config.list_physical_devices('GPU')
if gpus:
    tf.config.experimental.set_memory_growth(gpus[0], True)


plt.style.use(['seaborn-v0_8-colorblind', 'seaborn-v0_8-darkgrid'])
plt.show()
plt.rcParams.update({'font.size': 18})

np.set_printoptions(suppress=True, precision=3)

%load_ext autoreload
%autoreload 2

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
import os
project_path = '/content/drive/MyDrive/ColabNotebooks/project2'
os.chdir(project_path)

In [4]:
from conv_pcn_ext7 import (
    ConvPCNExt7,
    build_ext7_small,
    build_ext7_medium,
    build_ext7_deeper,
)
from conv_pcn_ext7_helpers import (
    set_global_seed,
    make_cifar_subset,
    describe_split,
    default_experiment_configs,
    run_with_project_api,
)

set_global_seed(42)
print(tf.__version__)

2.18.0

## 2) Load CIFAR dev data

In [5]:
from image_datasets import get_dataset, train_val_split
x_train, y_train, x_test, y_test = get_dataset('cifar10',flatten=False)

x_train shape: (50000, 32, 32, 3), dtype: <dtype: 'float32'>
y_train shape: (50000,), dtype: <dtype: 'int32'>
x_test shape: (10000, 32, 32, 3), dtype: <dtype: 'float32'>
y_test shape: (10000,), dtype: <dtype: 'int32'>

In [6]:
N = 3000

# random subset indices
idx = np.random.choice(len(x_train), size=N, replace=False)

x_sub = tf.gather(x_train, idx)
y_sub = tf.gather(y_train, idx)

val_fraction = 0.2
val_size = int(N * val_fraction)

x_val = tf.constant(x_sub[:val_size], dtype=tf.float32)
y_val = tf.constant(y_sub[:val_size], dtype=tf.int32)

x_train_small = tf.constant(x_sub[val_size:], dtype=tf.float32)
y_train_small = tf.constant(y_sub[val_size:], dtype=tf.int32)

print("train:", x_train_small.shape)
print("val:", x_val.shape)

class Split:
    def __init__(self, x_train, y_train, x_val, y_val):
        self.x_train = x_train
        self.y_train = y_train
        self.x_val = x_val
        self.y_val = y_val

split = Split(x_train_small, y_train_small, x_val, y_val)

train: (2400, 32, 32, 3)
val: (600, 32, 32, 3)

## 4) Sanity-check one model instance

In [7]:
num_classes = int(tf.reduce_max(y_train_small).numpy()) + 1
input_shape = tuple(x_train_small.shape[1:])

model = build_ext7_small(input_shape, num_classes)
print(model)

# Forward-pass sanity check on a tiny batch
sanity_logits = model(split.x_train[:4])
print('sanity output shape:', sanity_logits.shape)

<conv_pcn_ext7.ConvPCNExt7 object at 0x7e347e07ded0>
sanity output shape: (4, 10)

## 5) What the modified block is doing

1. **Feedforward conv** to initialize the latent state
2. **Feedback transposed conv** to reconstruct the lower layer
3. **1x1 bypass conv** to carry the lower-layer signal directly to the block output

In [8]:
from conv_pcn_ext7_blocks import ConvPCNBlockBypass
#help(ConvPCNBlockBypass)

## 6) Train a single fast baseline-style Extension 7 model

In [9]:
print("x_train:", split.x_train.shape, "y_train:", split.y_train.shape)
print("x_val:", split.x_val.shape, "y_val:", split.y_val.shape)

x_train: (2400, 32, 32, 3) y_train: (2400,)
x_val: (600, 32, 32, 3) y_val: (600,)

In [10]:
small_model = build_ext7_small(input_shape, num_classes)

small_history, small_result = run_with_project_api(
    model=small_model,
    split=split,
    epochs=5,
    batch_size=32,
    lr=1e-3,
)

print(small_result)

---------------------------------------------------------------------------
Dense layer output(Dense_output) shape: [1, 10]
Dense layer output(Dense_hidden) shape: [1, 96]
Dropout layer output(Dropout) shape: [1, 8192]
Flatten layer output(Flatten) shape: [1, 8192]
MaxPool2D layer output(MaxPool_2) shape: [1, 8, 8, 128]
PCNBlockExt7_2:
	Conv2D layer output(PCNBlockExt7_2_bypass) shape: [1, 16, 16, 128]
	Conv2DTranspose layer output(PCNBlockExt7_2_convT) shape: [1, 16, 16, 96]
	Conv2D layer output(PCNBlockExt7_2_conv) shape: [1, 16, 16, 128]
MaxPool2D layer output(MaxPool_1) shape: [1, 16, 16, 96]
PCNBlockExt7_1:
	Conv2D layer output(PCNBlockExt7_1_bypass) shape: [1, 32, 32, 96]
	Conv2DTranspose layer output(PCNBlockExt7_1_convT) shape: [1, 32, 32, 64]
	Conv2D layer output(PCNBlockExt7_1_conv) shape: [1, 32, 32, 96]
PCNBlockExt7_0:
	Conv2D layer output(PCNBlockExt7_0_bypass) shape: [1, 32, 32, 64]
	Conv2DTranspose layer output(PCNBlockExt7_0_convT) shape: [1, 32, 32, 32]
	Conv2D layer output(PCNBlockExt7_0_conv) shape: [1, 32, 32, 64]
Conv2D layer output(Conv2D_init) shape: [1, 32, 32, 32]
---------------------------------------------------------------------------
Epoch 1/5 | Time : 6.71 s | train_loss: 3.0424 | val_loss: 2.2686 | val_acc: 0.2031

Epoch 2/5 | Time : 0.73 s | train_loss: 1.9965 | val_loss: 1.9664 | val_acc: 0.3125

Epoch 3/5 | Time : 0.74 s | train_loss: 1.7347 | val_loss: 1.8283 | val_acc: 0.3472

Epoch 4/5 | Time : 0.73 s | train_loss: 1.4434 | val_loss: 1.7962 | val_acc: 0.3681

Epoch 5/5 | Time : 0.73 s | train_loss: 1.1697 | val_loss: 1.6731 | val_acc: 0.4375

Finished training after 5 epochs!
ExperimentResult(name='ConvPCNExt7', runtime_sec=10.821554899215698, epoch_used=5, final_val_acc=0.4375, final_train_loss=1.1697456447283427, final_val_loss=1.673069887691074)

In [17]:
import pandas as pd

data = [
    {
        "Model": "Vanilla (Original)",
        "num_steps": 5,
        "PCN Units": "(64, 128, 192)",
        "MaxPool After Block": "(True, True, True)",
        "Bypass (Skip)": "No",
        "Depth (#blocks)": 3,
    },
    {
        "Model": "Ext7 Small",
        "num_steps": 1,
        "PCN Units": "(64, 96, 128)",
        "MaxPool After Block": "(False, True, True)",
        "Bypass (Skip)": "Yes",
        "Depth (#blocks)": 3,
    },
    {
        "Model": "Ext7 Medium",
        "num_steps": 5,
        "PCN Units": "(64, 128, 128, 192)",
        "MaxPool After Block": "(False, False, True, True)",
        "Bypass (Skip)": "Yes",
        "Depth (#blocks)": 4,
    },
    {
        "Model": "Ext7 Deeper",
        "num_steps": 7,
        "PCN Units": "(64, 96, 128, 192, 192)",
        "MaxPool After Block": "(False, True, False, True, True)",
        "Bypass (Skip)": "Yes",
        "Depth (#blocks)": 5,
    },
]

df = pd.DataFrame(data)
df

,Model,num_steps,PCN Units,MaxPool After Block,Bypass (Skip),Depth (#blocks)
0,Vanilla (Original),5,"(64, 128, 192)","(True, True, True)",No,3
1,Ext7 Small,1,"(64, 96, 128)","(False, True, True)",Yes,3
2,Ext7 Medium,5,"(64, 128, 128, 192)","(False, False, True, True)",Yes,4
3,Ext7 Deeper,7,"(64, 96, 128, 192, 192)","(False, True, False, True, True)",Yes,5

In [11]:
results = []
configs = default_experiment_configs()

builders = {
    'build_ext7_small': build_ext7_small,
    'build_ext7_medium': build_ext7_medium,
    'build_ext7_deeper': build_ext7_deeper,
}

for cfg in configs:
    print('Running config:', cfg['name'])

    model = builders[cfg['builder']](input_shape, num_classes)
    _, result = run_with_project_api(
        model=model,
        split=split,
        epochs=cfg['epochs'],
        batch_size=32,
        lr=cfg['lr'],
    )
    result.name = cfg['name']
    results.append(result)
    print(result)

Running config: small_fast
---------------------------------------------------------------------------
Dense layer output(Dense_output) shape: [1, 10]
Dense layer output(Dense_hidden) shape: [1, 96]
Dropout layer output(Dropout) shape: [1, 8192]
Flatten layer output(Flatten) shape: [1, 8192]
MaxPool2D layer output(MaxPool_2) shape: [1, 8, 8, 128]
PCNBlockExt7_2:
	Conv2D layer output(PCNBlockExt7_2_bypass) shape: [1, 16, 16, 128]
	Conv2DTranspose layer output(PCNBlockExt7_2_convT) shape: [1, 16, 16, 96]
	Conv2D layer output(PCNBlockExt7_2_conv) shape: [1, 16, 16, 128]
MaxPool2D layer output(MaxPool_1) shape: [1, 16, 16, 96]
PCNBlockExt7_1:
	Conv2D layer output(PCNBlockExt7_1_bypass) shape: [1, 32, 32, 96]
	Conv2DTranspose layer output(PCNBlockExt7_1_convT) shape: [1, 32, 32, 64]
	Conv2D layer output(PCNBlockExt7_1_conv) shape: [1, 32, 32, 96]
PCNBlockExt7_0:
	Conv2D layer output(PCNBlockExt7_0_bypass) shape: [1, 32, 32, 64]
	Conv2DTranspose layer output(PCNBlockExt7_0_convT) shape: [1, 32, 32, 32]
	Conv2D layer output(PCNBlockExt7_0_conv) shape: [1, 32, 32, 64]
Conv2D layer output(Conv2D_init) shape: [1, 32, 32, 32]
---------------------------------------------------------------------------
Epoch 1/5000 | Time : 3.80 s | train_loss: 2.4973 | val_loss: 1.9772 | val_acc: 0.3212

Epoch 2/5000 | Time : 0.73 s | train_loss: 1.7659 | val_loss: 1.7698 | val_acc: 0.4062

Epoch 3/5000 | Time : 0.73 s | train_loss: 1.3445 | val_loss: 1.6721 | val_acc: 0.4340

Epoch 4/5000 | Time : 0.73 s | train_loss: 1.0785 | val_loss: 1.8085 | val_acc: 0.4062

Epoch 5/5000 | Time : 0.74 s | train_loss: 0.8723 | val_loss: 1.7664 | val_acc: 0.4757

Epoch 6/5000 | Time : 0.73 s | train_loss: 0.6577 | val_loss: 1.6496 | val_acc: 0.4965

Epoch 7/5000 | Time : 0.74 s | train_loss: 0.4553 | val_loss: 1.9036 | val_acc: 0.4896

Epoch 8/5000 | Time : 0.74 s | train_loss: 0.2932 | val_loss: 2.0144 | val_acc: 0.5052

Epoch 9/5000 | Time : 0.74 s | train_loss: 0.2589 | val_loss: 2.2816 | val_acc: 0.5035
Learning rate decayed from 0.001000 to 0.000500.
 | LR decayed. Total decays: 1
Epoch 10/5000 | Time : 0.74 s | train_loss: 0.1440 | val_loss: 2.1554 | val_acc: 0.4931
Learning rate decayed from 0.000500 to 0.000250.
 | LR decayed. Total decays: 2
Epoch 11/5000 | Time : 0.74 s | train_loss: 0.0808 | val_loss: 2.1685 | val_acc: 0.5122
Learning rate decayed from 0.000250 to 0.000125.
 | LR decayed. Total decays: 3
Epoch 12/5000 | Time : 0.74 s | train_loss: 0.0464 | val_loss: 2.1837 | val_acc: 0.5122

Epoch 13/5000 | Time : 0.75 s | train_loss: 0.0470 | val_loss: 2.1960 | val_acc: 0.5035

Early stopping triggered. Stopping training.
Finished training after 13 epochs!
ExperimentResult(name='small_fast', runtime_sec=14.88190746307373, epoch_used=13, final_val_acc=0.5034722222222222, final_train_loss=0.04704525583734115, final_val_loss=2.1959861119588218)
Running config: medium_paper
---------------------------------------------------------------------------
Dense layer output(Dense_output) shape: [1, 10]
Dense layer output(Dense_hidden) shape: [1, 128]
Dropout layer output(Dropout) shape: [1, 12288]
Flatten layer output(Flatten) shape: [1, 12288]
MaxPool2D layer output(MaxPool_3) shape: [1, 8, 8, 192]
PCNBlockExt7_3:
	Conv2D layer output(PCNBlockExt7_3_bypass) shape: [1, 16, 16, 192]
	Conv2DTranspose layer output(PCNBlockExt7_3_convT) shape: [1, 16, 16, 128]
	Conv2D layer output(PCNBlockExt7_3_conv) shape: [1, 16, 16, 192]
MaxPool2D layer output(MaxPool_2) shape: [1, 16, 16, 128]
PCNBlockExt7_2:
	Conv2D layer output(PCNBlockExt7_2_bypass) shape: [1, 32, 32, 128]
	Conv2DTranspose layer output(PCNBlockExt7_2_convT) shape: [1, 32, 32, 128]
	Conv2D layer output(PCNBlockExt7_2_conv) shape: [1, 32, 32, 128]
PCNBlockExt7_1:
	Conv2D layer output(PCNBlockExt7_1_bypass) shape: [1, 32, 32, 128]
	Conv2DTranspose layer output(PCNBlockExt7_1_convT) shape: [1, 32, 32, 64]
	Conv2D layer output(PCNBlockExt7_1_conv) shape: [1, 32, 32, 128]
PCNBlockExt7_0:
	Conv2D layer output(PCNBlockExt7_0_bypass) shape: [1, 32, 32, 64]
	Conv2DTranspose layer output(PCNBlockExt7_0_convT) shape: [1, 32, 32, 64]
	Conv2D layer output(PCNBlockExt7_0_conv) shape: [1, 32, 32, 64]
Conv2D layer output(Conv2D_init) shape: [1, 32, 32, 64]
---------------------------------------------------------------------------
Epoch 1/5000 | Time : 9.52 s | train_loss: 32.8747 | val_loss: 33.2596 | val_acc: 0.0972

Epoch 2/5000 | Time : 3.99 s | train_loss: 33.1726 | val_loss: 33.2596 | val_acc: 0.0972

Epoch 3/5000 | Time : 3.98 s | train_loss: 33.3107 | val_loss: 33.2596 | val_acc: 0.0972

Epoch 4/5000 | Time : 4.01 s | train_loss: 33.0805 | val_loss: 33.2596 | val_acc: 0.0972
Learning rate decayed from 0.001000 to 0.000500.
 | LR decayed. Total decays: 1
Epoch 5/5000 | Time : 3.98 s | train_loss: 33.3568 | val_loss: 33.2596 | val_acc: 0.0972
Learning rate decayed from 0.000500 to 0.000250.
 | LR decayed. Total decays: 2
Epoch 6/5000 | Time : 3.96 s | train_loss: 33.4796 | val_loss: 33.2596 | val_acc: 0.0972
Learning rate decayed from 0.000250 to 0.000125.
 | LR decayed. Total decays: 3
Epoch 7/5000 | Time : 3.97 s | train_loss: 33.2954 | val_loss: 33.2596 | val_acc: 0.0972
Learning rate decayed from 0.000125 to 0.000063.
 | LR decayed. Total decays: 4
Epoch 8/5000 | Time : 3.95 s | train_loss: 32.8042 | val_loss: 33.2596 | val_acc: 0.0972

Early stopping triggered. Stopping training.
Finished training after 8 epochs!
ExperimentResult(name='medium_paper', runtime_sec=43.46081256866455, epoch_used=8, final_val_acc=0.09722222222222222, final_train_loss=32.80416186014811, final_val_loss=33.259562174479164)
Running config: deeper_pooled
---------------------------------------------------------------------------
Dense layer output(Dense_output) shape: [1, 10]
Dense layer output(Dense_hidden) shape: [1, 128]
Dropout layer output(Dropout) shape: [1, 3072]
Flatten layer output(Flatten) shape: [1, 3072]
MaxPool2D layer output(MaxPool_4) shape: [1, 4, 4, 192]
PCNBlockExt7_4:
	Conv2D layer output(PCNBlockExt7_4_bypass) shape: [1, 8, 8, 192]
	Conv2DTranspose layer output(PCNBlockExt7_4_convT) shape: [1, 8, 8, 192]
	Conv2D layer output(PCNBlockExt7_4_conv) shape: [1, 8, 8, 192]
MaxPool2D layer output(MaxPool_3) shape: [1, 8, 8, 192]
PCNBlockExt7_3:
	Conv2D layer output(PCNBlockExt7_3_bypass) shape: [1, 16, 16, 192]
	Conv2DTranspose layer output(PCNBlockExt7_3_convT) shape: [1, 16, 16, 128]
	Conv2D layer output(PCNBlockExt7_3_conv) shape: [1, 16, 16, 192]
PCNBlockExt7_2:
	Conv2D layer output(PCNBlockExt7_2_bypass) shape: [1, 16, 16, 128]
	Conv2DTranspose layer output(PCNBlockExt7_2_convT) shape: [1, 16, 16, 96]
	Conv2D layer output(PCNBlockExt7_2_conv) shape: [1, 16, 16, 128]
MaxPool2D layer output(MaxPool_1) shape: [1, 16, 16, 96]
PCNBlockExt7_1:
	Conv2D layer output(PCNBlockExt7_1_bypass) shape: [1, 32, 32, 96]
	Conv2DTranspose layer output(PCNBlockExt7_1_convT) shape: [1, 32, 32, 64]
	Conv2D layer output(PCNBlockExt7_1_conv) shape: [1, 32, 32, 96]
PCNBlockExt7_0:
	Conv2D layer output(PCNBlockExt7_0_bypass) shape: [1, 32, 32, 64]
	Conv2DTranspose layer output(PCNBlockExt7_0_convT) shape: [1, 32, 32, 64]
	Conv2D layer output(PCNBlockExt7_0_conv) shape: [1, 32, 32, 64]
Conv2D layer output(Conv2D_init) shape: [1, 32, 32, 64]
---------------------------------------------------------------------------
Epoch 1/5000 | Time : 11.15 s | train_loss: 7.3629 | val_loss: 2.1006 | val_acc: 0.2274

Epoch 2/5000 | Time : 3.95 s | train_loss: 1.8330 | val_loss: 1.8611 | val_acc: 0.3212

Epoch 3/5000 | Time : 3.95 s | train_loss: 1.5421 | val_loss: 1.6805 | val_acc: 0.4184

Epoch 4/5000 | Time : 3.95 s | train_loss: 1.2759 | val_loss: 1.5599 | val_acc: 0.4618

Epoch 5/5000 | Time : 3.99 s | train_loss: 1.0781 | val_loss: 1.5748 | val_acc: 0.4878

Epoch 6/5000 | Time : 3.98 s | train_loss: 0.8858 | val_loss: 1.5271 | val_acc: 0.5052

Epoch 7/5000 | Time : 4.00 s | train_loss: 0.7070 | val_loss: 1.6037 | val_acc: 0.5017

Epoch 8/5000 | Time : 3.99 s | train_loss: 0.5509 | val_loss: 1.7993 | val_acc: 0.5069

Epoch 9/5000 | Time : 3.98 s | train_loss: 0.4772 | val_loss: 1.7919 | val_acc: 0.5382
Learning rate decayed from 0.001000 to 0.000500.
 | LR decayed. Total decays: 1
Epoch 10/5000 | Time : 4.00 s | train_loss: 0.2404 | val_loss: 1.6711 | val_acc: 0.5642
Learning rate decayed from 0.000500 to 0.000250.
 | LR decayed. Total decays: 2
Epoch 11/5000 | Time : 3.97 s | train_loss: 0.1376 | val_loss: 1.6892 | val_acc: 0.5729

Epoch 12/5000 | Time : 3.98 s | train_loss: 0.0823 | val_loss: 1.7496 | val_acc: 0.5694

Epoch 13/5000 | Time : 3.97 s | train_loss: 0.0598 | val_loss: 1.8495 | val_acc: 0.5556

Early stopping triggered. Stopping training.
Finished training after 13 epochs!
ExperimentResult(name='deeper_pooled', runtime_sec=72.50628232955933, epoch_used=13, final_val_acc=0.5555555555555556, final_train_loss=0.05975380847851435, final_val_loss=1.8495391209920247)

## 8) Turn results into a table

This cell makes it easier to read off your final report claims.
In particular, look for whether the bypass + pooling schedule helps validation accuracy enough to justify the extra runtime.

In [12]:
import pandas as pd

rows = []
for r in results:
    rows.append({
        'name': r.name,
        'runtime_sec': r.runtime_sec,
        'epoch_used': r.epoch_used,
        'final_val_acc': r.final_val_acc,
        'final_train_loss': r.final_train_loss,
        'final_val_loss': r.final_val_loss,
    })

results_df = pd.DataFrame(rows)
results_df.sort_values('final_val_acc', ascending=False)

,name,runtime_sec,epoch_used,final_val_acc,final_train_loss,final_val_loss
2,deeper_pooled,72.506282,13,0.555556,0.059754,1.849539
0,small_fast,14.881907,13,0.503472,0.047045,2.195986
1,medium_paper,43.460813,8,0.097222,32.804162,33.259562

In [13]:
from conv_pcn import ConvPCN7XL
big_model = ConvPCN7XL(
    input_feats_shape=split.x_train.shape[1:],
    C=10
)
big_model.compile(lr=1e-4)
btrain_loss, bval_loss, bval_acc, _ = big_model.fit(
    split.x_train, split.y_train,
    split.x_val, split.y_val,
    batch_size=32,
    max_epochs=50,
    patience=7,
    lr_patience=3,
    lr_max_decays=3,
)

---------------------------------------------------------------------------
Dense layer output(Dense_output) shape: [1, 10]
Dense layer output(Dense_hidden) shape: [1, 128]
Dropout layer output(Dropout) shape: [1, 16384]
Flatten layer output(Flatten) shape: [1, 16384]
MaxPool2D layer output(MaxPool_3) shape: [1, 8, 8, 256]
PCNBlock_3:
	Conv2DTranspose layer output(PCNBlock_3_convT) shape: [1, 16, 16, 256]
	Conv2D layer output(PCNBlock_3_conv) shape: [1, 16, 16, 256]
MaxPool2D layer output(MaxPool_2) shape: [1, 16, 16, 256]
PCNBlock_2:
	Conv2DTranspose layer output(PCNBlock_2_convT) shape: [1, 32, 32, 128]
	Conv2D layer output(PCNBlock_2_conv) shape: [1, 32, 32, 256]
PCNBlock_1:
	Conv2DTranspose layer output(PCNBlock_1_convT) shape: [1, 32, 32, 128]
	Conv2D layer output(PCNBlock_1_conv) shape: [1, 32, 32, 128]
PCNBlock_0:
	Conv2DTranspose layer output(PCNBlock_0_convT) shape: [1, 32, 32, 64]
	Conv2D layer output(PCNBlock_0_conv) shape: [1, 32, 32, 128]
Conv2D layer output(Conv2D_init) shape: [1, 32, 32, 64]
---------------------------------------------------------------------------
Epoch 1/50 | Time : 28.76 s | train_loss: 3.6732 | val_loss: 2.5434 | val_acc: 0.1667

Epoch 2/50 | Time : 18.33 s | train_loss: 2.0973 | val_loss: 1.9797 | val_acc: 0.2691

Epoch 3/50 | Time : 18.25 s | train_loss: 1.8832 | val_loss: 2.0391 | val_acc: 0.3247

Epoch 4/50 | Time : 18.15 s | train_loss: 1.7547 | val_loss: 1.9196 | val_acc: 0.3455

Epoch 5/50 | Time : 18.15 s | train_loss: 1.5872 | val_loss: 1.8150 | val_acc: 0.3958

Epoch 6/50 | Time : 18.19 s | train_loss: 1.3760 | val_loss: 1.8124 | val_acc: 0.3889

Epoch 7/50 | Time : 18.22 s | train_loss: 1.1963 | val_loss: 2.0181 | val_acc: 0.4097

Epoch 8/50 | Time : 18.22 s | train_loss: 0.9322 | val_loss: 1.9855 | val_acc: 0.4375

Epoch 9/50 | Time : 18.19 s | train_loss: 0.8764 | val_loss: 2.1295 | val_acc: 0.4375
Learning rate decayed from 0.000100 to 0.000050.
 | LR decayed. Total decays: 1
Epoch 10/50 | Time : 18.19 s | train_loss: 0.5477 | val_loss: 2.0143 | val_acc: 0.4323

Epoch 11/50 | Time : 18.20 s | train_loss: 0.4355 | val_loss: 2.0330 | val_acc: 0.4722
Learning rate decayed from 0.000050 to 0.000025.
 | LR decayed. Total decays: 2
Epoch 12/50 | Time : 18.20 s | train_loss: 0.3174 | val_loss: 2.1139 | val_acc: 0.4635

Epoch 13/50 | Time : 18.19 s | train_loss: 0.2906 | val_loss: 2.0133 | val_acc: 0.4653

Early stopping triggered. Stopping training.
Finished training after 13 epochs!